/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.copyofrotasystem;

import java.sql.*;

/**
 *
 * @author josephturner
 */
public class CalculateStaffPay extends javax.swing.JFrame {
    int staffID;
    String firstName;
    static User user;
    DAO db;
    /**
     * Creates new form CalculateStaffPay
     */
    public CalculateStaffPay(User user) {
        initComponents();
        this.user = user;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        StaffMember = new javax.swing.JLabel();
        StaffMemberField = new javax.swing.JComboBox<>();
        btnGetStaffDetails = new javax.swing.JButton();
        HoursWorked = new javax.swing.JLabel();
        RateOfPay = new javax.swing.JLabel();
        NIContribution = new javax.swing.JLabel();
        TotalPay = new javax.swing.JLabel();
        HoursWorkedField = new javax.swing.JTextField();
        RateOfPayField = new javax.swing.JTextField();
        NIContributionField = new javax.swing.JTextField();
        TotalPayField = new javax.swing.JTextField();
        btnPrintPayslip = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Title.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        Title.setText("Calculate Staff Pay");

        StaffMember.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        StaffMember.setText("Staff Member:");
        StaffMember.setToolTipText("");

        btnGetStaffDetails.setText("Get Staff Details");
        btnGetStaffDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetStaffDetailsActionPerformed(evt);
            }
        });

        HoursWorked.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        HoursWorked.setText("Number of Hours Worked:");

        RateOfPay.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        RateOfPay.setText("Rate of Pay:");

        NIContribution.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        NIContribution.setText("National Insurance Contribution:");

        TotalPay.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        TotalPay.setText("Total Pay:");

        HoursWorkedField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N

        RateOfPayField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N

        NIContributionField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N

        TotalPayField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        TotalPayField.setText("£");

        btnPrintPayslip.setBackground(new java.awt.Color(128, 191, 180));
        btnPrintPayslip.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnPrintPayslip.setText("Print Payslip");

        BackButton.setBackground(new java.awt.Color(128, 191, 180));
        BackButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        BackButton.setText("Back");
        BackButton.setToolTipText("");
        BackButton.setPreferredSize(new java.awt.Dimension(103, 54));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                                .addComponent(btnGetStaffDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(StaffMember)
                                .addGap(18, 18, 18)
                                .addComponent(StaffMemberField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(TotalPay)
                                            .addComponent(HoursWorked)
                                            .addComponent(RateOfPay)
                                            .addComponent(NIContribution)))
                                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPrintPayslip)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(HoursWorkedField)
                                        .addComponent(RateOfPayField)
                                        .addComponent(NIContributionField)
                                        .addComponent(TotalPayField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(Title)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StaffMember)
                    .addComponent(StaffMemberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGetStaffDetails)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoursWorked)
                    .addComponent(HoursWorkedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RateOfPay)
                    .addComponent(RateOfPayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIContribution)
                    .addComponent(NIContributionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalPayField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalPay))
                        .addGap(18, 18, 18)
                        .addComponent(btnPrintPayslip, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetStaffDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetStaffDetailsActionPerformed
        float hoursWorked = 0;
        float rateOfPay = 0;
        float pay = 0;
        float NIContribution = 0;
        String staffName = (String) StaffMemberField.getSelectedItem();
        String[] nameParts = staffName.split(" ");
        int staffID = Integer.valueOf(nameParts[0]);
        String firstName = nameParts[2];
        String surname = nameParts[3];
        try {
            ResultSet rs = db.CalculateStaffPay(staffID); 
            while (rs.next()) {
                rateOfPay = rs.getFloat("rateofpay");
                String startTime = rs.getString("starttime");
                String endTime = rs.getString("endtime");
                float shiftHours = db.CalculateHoursWorked(startTime, endTime);
                hoursWorked = hoursWorked + shiftHours;    
            }
            pay = pay + (rateOfPay * hoursWorked);

            if (pay < 242) {
                NIContribution = 0;
            }
            else if (pay > 242 && pay < 967) {
                NIContribution = (float) ((pay - 242) * 0.12);
            }
            else {
                NIContribution = (float) (93.24 + ((pay - 967) * 0.02));
            }
            } catch(Exception e) {
                
        }
            HoursWorkedField.setText(Float.toString(hoursWorked));
            RateOfPayField.setText("£" + Float.toString(rateOfPay));   
            NIContributionField.setText("£" + Float.toString(NIContribution));
            TotalPayField.setText("£" + Float.toString(pay - NIContribution));
    }//GEN-LAST:event_btnGetStaffDetailsActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        StaffMainMenu smm = new StaffMainMenu(user);
        smm.setVisible(true);
        smm.ShiftsHeader.setText(firstName + "'s upcoming shifts:");
        smm.Title.setText("Welcome, " + firstName);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            ResultSet rs = db.GenerateStaffList();          
            while (rs.next()) {
                String name = rs.getInt("staffid") + " - " + rs.getString("firstname") + " " + rs.getString("surname");
                StaffMemberField.addItem(name);
                }
            } catch(Exception e) {
                
        }        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculateStaffPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculateStaffPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculateStaffPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculateStaffPay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculateStaffPay(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel HoursWorked;
    private javax.swing.JTextField HoursWorkedField;
    private javax.swing.JLabel NIContribution;
    private javax.swing.JTextField NIContributionField;
    private javax.swing.JLabel RateOfPay;
    private javax.swing.JTextField RateOfPayField;
    private javax.swing.JLabel StaffMember;
    private javax.swing.JComboBox<String> StaffMemberField;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel TotalPay;
    private javax.swing.JTextField TotalPayField;
    private javax.swing.JButton btnGetStaffDetails;
    private javax.swing.JButton btnPrintPayslip;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
