/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.copyofrotasystem;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Color;

/**
 *
 * @author josephturner
 */
public class ForgotPassword extends javax.swing.JFrame {
    DAO db = new DAO();
    Color red = new Color(255,0,0);
    Color black = new Color(0,0,0);

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
        AnswerField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChangePasswordForm = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        PasswordErrorMessage = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        PasswordRequirementBox = new javax.swing.JScrollPane();
        lblPasswordRequirement = new javax.swing.JTextArea();
        lblConfirmPassword = new javax.swing.JLabel();
        ConfirmPasswordField = new javax.swing.JPasswordField();
        btnSubmitNewPassword = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblForgotPassword = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        btnGetSecurityQuestion = new javax.swing.JButton();
        subSecurityQuestion = new javax.swing.JLabel();
        lblSecurityQuestion = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        lblAnswer = new javax.swing.JLabel();
        AnswerField = new javax.swing.JTextField();
        btnSubmitAnswer = new javax.swing.JButton();
        ErrorMessage = new javax.swing.JLabel();

        ChangePasswordForm.setSize(new java.awt.Dimension(531, 389));

        PasswordErrorMessage.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        PasswordErrorMessage.setForeground(new java.awt.Color(255, 0, 0));

        lblPassword.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lblPassword.setText("New Password:");

        PasswordField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        lblPasswordRequirement.setEditable(false);
        lblPasswordRequirement.setColumns(20);
        lblPasswordRequirement.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblPasswordRequirement.setRows(5);
        lblPasswordRequirement.setText("Your password must contain:\n- 8+ Characters\n- An uppercase character\n- A number\n- A special character");
        PasswordRequirementBox.setViewportView(lblPasswordRequirement);

        lblConfirmPassword.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        lblConfirmPassword.setText("Confirm New Password:");

        ConfirmPasswordField.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N

        btnSubmitNewPassword.setBackground(new java.awt.Color(128, 191, 180));
        btnSubmitNewPassword.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnSubmitNewPassword.setText("Submit New Password");
        btnSubmitNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitNewPasswordActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(128, 191, 180));
        btnCancel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PasswordRequirementBox)
                            .addComponent(PasswordField)
                            .addComponent(ConfirmPasswordField)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addGap(78, 78, 78)
                        .addComponent(btnSubmitNewPassword)))
                .addContainerGap(11, Short.MAX_VALUE))
            .addComponent(PasswordErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordRequirementBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblConfirmPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConfirmPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(PasswordErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSubmitNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );

        javax.swing.GroupLayout ChangePasswordFormLayout = new javax.swing.GroupLayout(ChangePasswordForm.getContentPane());
        ChangePasswordForm.getContentPane().setLayout(ChangePasswordFormLayout);
        ChangePasswordFormLayout.setHorizontalGroup(
            ChangePasswordFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangePasswordFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ChangePasswordFormLayout.setVerticalGroup(
            ChangePasswordFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangePasswordFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblForgotPassword.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        lblForgotPassword.setText("Forgot Password");

        lblUsername.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        lblUsername.setText("Username:");

        UsernameField.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N

        btnGetSecurityQuestion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnGetSecurityQuestion.setText("Get Security Question");
        btnGetSecurityQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetSecurityQuestionActionPerformed(evt);
            }
        });

        subSecurityQuestion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        subSecurityQuestion.setText("Your Security Question:");

        lblSecurityQuestion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblSecurityQuestion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BackButton.setBackground(new java.awt.Color(128, 191, 180));
        BackButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        BackButton.setText("Back");
        BackButton.setToolTipText("");
        BackButton.setPreferredSize(new java.awt.Dimension(103, 54));
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        lblAnswer.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lblAnswer.setText("Answer:");

        AnswerField.setPreferredSize(new java.awt.Dimension(64, 35));

        btnSubmitAnswer.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnSubmitAnswer.setText("Submit Answer");
        btnSubmitAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitAnswerActionPerformed(evt);
            }
        });

        ErrorMessage.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        ErrorMessage.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(subSecurityQuestion)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSecurityQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(btnGetSecurityQuestion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(btnSubmitAnswer)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addComponent(lblForgotPassword))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblAnswer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(AnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblUsername)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 86, Short.MAX_VALUE))
                    .addComponent(ErrorMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblForgotPassword)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UsernameField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGetSecurityQuestion)
                .addGap(24, 24, 24)
                .addComponent(subSecurityQuestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSecurityQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AnswerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmitAnswer)
                .addGap(18, 18, 18)
                .addComponent(ErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetSecurityQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetSecurityQuestionActionPerformed
        String username = UsernameField.getText(); // Stores the username entered by the user
        String secQ = ""; // Empties the security question string
        try {
            ResultSet rs = db.ReturnSecQ(username); // SQL Statement - Returns the staff member's security question
            if (rs.next()) {
                secQ = rs.getString("securityquestion"); // Stores the security question
                lblSecurityQuestion.setForeground(black);
                lblSecurityQuestion.setText(secQ); // Displays the security question on the screen
                AnswerField.setEditable(true); // Allows the user to input their answer
            } else {
                lblSecurityQuestion.setForeground(red); // Sets the text colour to red
                lblSecurityQuestion.setText("User not found!"); // Displays an error message to tell the user that the account has not been found
                AnswerField.setEditable(false); // Does not allow the user to enter an answer
            }
      
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_btnGetSecurityQuestionActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        LoginScreen ls = new LoginScreen(); // Creates an instance of the Login Screen
        ls.setVisible(true); // Makes the Login Screen visible
        this.dispose(); // Closes the Forgot Password screen
    }//GEN-LAST:event_BackButtonActionPerformed

    private void btnSubmitAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitAnswerActionPerformed
        boolean matching = false;
        String username = UsernameField.getText(); // Stores the username entered by the user
        try {
            ResultSet rs = db.ReturnSecQ(username); // SQL Statement - Returns the user's security question and answer
            while (rs.next()) {
                if (AnswerField.getText().equals(rs.getString("secqanswer"))) { // If answer given by user matches answer in the database
                    matching = true;
                }
            }
            if (matching == true) { 
                ErrorMessage.setText(""); // Clears error message box
                ChangePasswordForm.setVisible(true); // Makes Change Password form visible
                jPanel2.setVisible(true); // Makes Change Password form visible
            } else {
                ErrorMessage.setText("Error - The answer you have submitted does not match our records!"); // Displays error message telling user that the answer does not match
            }
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_btnSubmitAnswerActionPerformed

    private void btnSubmitNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitNewPasswordActionPerformed
        String password = PasswordField.getText(); // Password is equal to the password entered by the user
        if (CheckPassword(password) == false) { // If the new password does not meet the criteria
            PasswordErrorMessage.setText("Error - Password does not match criteria!"); // Displays error message telling user that password doesn't meet the criteria
        } else if (PasswordField.getText().equals("")) { // If the password field is empty
            PasswordErrorMessage.setText("Error - Password is missing!"); // Displays error message telling user that password field is empty
        } else if (!(ConfirmPasswordField.getText().equals(PasswordField.getText()))) { // If Password field and Confirm Password field do not match
            PasswordErrorMessage.setText("Error - Passwords must match!"); // Displays error message telling user that passwords must match
        } else {
            try {
                int userSuccess = db.ChangePassword(UsernameField.getText(), password); // SQL Statement - Updates user password within the database
                if (userSuccess > 0) { // If password is saved successfully
                    LoginScreen ls = new LoginScreen(); // Creates an instance of the Login Screen
                    ls.setVisible(true); // Makes the Login Screen visible
                    dispose(); // Closes the Forgot Password and Submit New Password screen
                } else {
                    PasswordErrorMessage.setText("Error!"); // Displays when the password is not saved successfully
                }
            } catch (Exception e) {
                
            }   
        }
    }//GEN-LAST:event_btnSubmitNewPasswordActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        LoginScreen ls = new LoginScreen(); // Creates an instance of the Login Screen
        ls.setVisible(true); // Makes the Login Screen visible
        dispose(); // Closes the Forgot Password and Submit New Password screen
    }//GEN-LAST:event_btnCancelActionPerformed

    
    private boolean CheckPassword(String password) {
        Boolean uppercase = false;
        Boolean number = false;
        Boolean special = false;
        Boolean length = false;
        if (password.length() >= 8) {
            length = true;
        } else {
            return false;
        }
        char[] characters = password.toCharArray();
        for (char character : characters) {
            if (Character.isUpperCase(character)) {
                uppercase = true;
            }
            if (Character.isDigit(character)) {
                number = true;
            }
            if (!Character.isLetterOrDigit(character)) {
                special = true;
            }
        }
        if (uppercase == true && number == true && special == true && length == true) {
            return true;
        } else {
            return false;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnswerField;
    private javax.swing.JButton BackButton;
    private javax.swing.JFrame ChangePasswordForm;
    private javax.swing.JPasswordField ConfirmPasswordField;
    private javax.swing.JLabel ErrorMessage;
    private javax.swing.JLabel PasswordErrorMessage;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JScrollPane PasswordRequirementBox;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGetSecurityQuestion;
    private javax.swing.JButton btnSubmitAnswer;
    private javax.swing.JButton btnSubmitNewPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAnswer;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblForgotPassword;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextArea lblPasswordRequirement;
    private javax.swing.JLabel lblSecurityQuestion;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel subSecurityQuestion;
    // End of variables declaration//GEN-END:variables
}
